from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1001, 883)
        # Add a QLabel for the logo in the upper right corner
        self.logoLabel = QtWidgets.QLabel(Dialog)
        self.logoLabel.setGeometry(QtCore.QRect(800, 22, 191, 30))
        pixmap = QtGui.QPixmap(
            'logo.png')  # Replace 'path/to/your/logo.png' with the actual path to your logo
        self.logoLabel.setPixmap(pixmap)
        self.logoLabel.setScaledContents(True)

        # Add a QLabel for the title in the center
        self.titleLabel = QtWidgets.QLabel(Dialog)
        self.titleLabel.setGeometry(QtCore.QRect(300, 10, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.titleLabel.setText("Digikap Web Scraper")
        self.configFileInputBox = QtWidgets.QPlainTextEdit(Dialog)
        self.configFileInputBox.setGeometry(QtCore.QRect(150, 100, 741, 31))
        self.configFileInputBox.setObjectName("configFileInputBox")
        self.selectByProductBtn = QtWidgets.QRadioButton(Dialog)
        self.selectByProductBtn.setGeometry(QtCore.QRect(150, 150, 151, 23))
        self.selectByProductBtn.setObjectName("selectByProductBtn")
        self.selectByConfigBtn = QtWidgets.QRadioButton(Dialog)
        self.selectByConfigBtn.setGeometry(QtCore.QRect(150, 70, 191, 23))
        self.selectByConfigBtn.setObjectName("selectByConfigBtn")
        self.productName1 = QtWidgets.QPlainTextEdit(Dialog)
        self.productName1.setGeometry(QtCore.QRect(150, 180, 181, 31))
        self.productName1.setObjectName("productName1")
        self.configLabel = QtWidgets.QLabel(Dialog)
        self.configLabel.setGeometry(QtCore.QRect(10, 100, 151, 31))
        self.configLabel.setObjectName("configLabel")
        self.productName2 = QtWidgets.QPlainTextEdit(Dialog)
        self.productName2.setGeometry(QtCore.QRect(150, 220, 181, 31))
        self.productName2.setObjectName("productName2")
        self.productName4 = QtWidgets.QPlainTextEdit(Dialog)
        self.productName4.setGeometry(QtCore.QRect(150, 300, 181, 31))
        self.productName4.setObjectName("productName4")
        self.productName3 = QtWidgets.QPlainTextEdit(Dialog)
        self.productName3.setGeometry(QtCore.QRect(150, 260, 181, 31))
        self.productName3.setObjectName("productName3")
        self.productName5 = QtWidgets.QPlainTextEdit(Dialog)
        self.productName5.setGeometry(QtCore.QRect(150, 340, 181, 31))
        self.productName5.setObjectName("productName5")
        self.productLink1 = QtWidgets.QPlainTextEdit(Dialog)
        self.productLink1.setGeometry(QtCore.QRect(340, 180, 551, 31))
        self.productLink1.setAutoFillBackground(False)
        self.productLink1.setObjectName("productLink1")
        self.productLink2 = QtWidgets.QPlainTextEdit(Dialog)
        self.productLink2.setGeometry(QtCore.QRect(340, 220, 551, 31))
        self.productLink2.setObjectName("productLink2")
        self.productLink3 = QtWidgets.QPlainTextEdit(Dialog)
        self.productLink3.setGeometry(QtCore.QRect(340, 260, 551, 31))
        self.productLink3.setObjectName("productLink3")
        self.productLink4 = QtWidgets.QPlainTextEdit(Dialog)
        self.productLink4.setGeometry(QtCore.QRect(340, 300, 551, 31))
        self.productLink4.setObjectName("productLink4")
        self.productLink5 = QtWidgets.QPlainTextEdit(Dialog)
        self.productLink5.setGeometry(QtCore.QRect(340, 340, 551, 31))
        self.productLink5.setObjectName("productLink5")
        self.configBrowse = QtWidgets.QPushButton(Dialog)
        self.configBrowse.setGeometry(QtCore.QRect(900, 100, 89, 31))
        self.configBrowse.setObjectName("configBrowse")
        self.outputFilePathInputBox = QtWidgets.QPlainTextEdit(Dialog)
        self.outputFilePathInputBox.setGeometry(QtCore.QRect(150, 410, 741, 31))
        self.outputFilePathInputBox.setObjectName("outputFilePathInputBox")
        self.outputFolderLabel = QtWidgets.QLabel(Dialog)
        self.outputFolderLabel.setGeometry(QtCore.QRect(40, 410, 151, 31))
        self.outputFolderLabel.setObjectName("outputFolderLabel")
        self.outputFolderBrowse = QtWidgets.QPushButton(Dialog)
        self.outputFolderBrowse.setGeometry(QtCore.QRect(900, 410, 89, 31))
        self.outputFolderBrowse.setObjectName("outputFolderBrowse")
        self.consoleLabel = QtWidgets.QLabel(Dialog)
        self.consoleLabel.setGeometry(QtCore.QRect(10, 510, 71, 20))
        self.consoleLabel.setObjectName("consoleLabel")
        self.consolTextEdit = QtWidgets.QTextEdit(Dialog)
        self.consolTextEdit.setGeometry(QtCore.QRect(10, 540, 981, 331))
        self.consolTextEdit.setObjectName("consolTextEdit")
        self.scrappingBtn = QtWidgets.QPushButton(Dialog)
        self.scrappingBtn.setGeometry(QtCore.QRect(450, 470, 111, 41))
        self.scrappingBtn.setObjectName("scrappingBtn")
        self.productlabel_1 = QtWidgets.QLabel(Dialog)
        self.productlabel_1.setGeometry(QtCore.QRect(70, 190, 67, 17))
        self.productlabel_1.setObjectName("productlabel_1")
        self.productlabel_2 = QtWidgets.QLabel(Dialog)
        self.productlabel_2.setGeometry(QtCore.QRect(70, 230, 67, 17))
        self.productlabel_2.setObjectName("productlabel_2")
        self.productlabel_3 = QtWidgets.QLabel(Dialog)
        self.productlabel_3.setGeometry(QtCore.QRect(70, 270, 67, 17))
        self.productlabel_3.setObjectName("productlabel_3")
        self.productlabel_4 = QtWidgets.QLabel(Dialog)
        self.productlabel_4.setGeometry(QtCore.QRect(70, 310, 67, 17))
        self.productlabel_4.setObjectName("productlabel_4")
        self.productlabel_5 = QtWidgets.QLabel(Dialog)
        self.productlabel_5.setGeometry(QtCore.QRect(70, 350, 67, 17))
        self.productlabel_5.setObjectName("productlabel_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Digiklap - Web Scraper UI"))
        self.configFileInputBox.setToolTip(_translate("Dialog", "Path to the config file"))
        self.selectByProductBtn.setToolTip(_translate("Dialog", "Enter product details manually"))
        self.selectByProductBtn.setText(_translate("Dialog", "Select By Product"))
        self.selectByConfigBtn.setToolTip(_translate("Dialog", "Select the predefined products from the config file"))
        self.selectByConfigBtn.setText(_translate("Dialog", "Select By Config file"))
        self.productName1.setToolTip(_translate("Dialog", "Provide a Product name (for your ref. only)"))
        self.configLabel.setText(_translate("Dialog", "Config File Location"))
        self.productName2.setToolTip(_translate("Dialog", "Provide a Product name (for your ref. only)"))
        self.productName4.setToolTip(_translate("Dialog", "Provide a Product name (for your ref. only)"))
        self.productName3.setToolTip(_translate("Dialog", "Provide a Product name (for your ref. only)"))
        self.productName5.setToolTip(_translate("Dialog", "Provide a Product name (for your ref. only)"))
        self.productLink1.setToolTip(_translate("Dialog", "provide a link of the review page"))
        self.productLink2.setToolTip(_translate("Dialog", "provide a link of the review page"))
        self.productLink3.setToolTip(_translate("Dialog", "provide a link of the review page"))
        self.productLink4.setToolTip(_translate("Dialog", "provide a link of the review page"))
        self.productLink5.setToolTip(_translate("Dialog", "provide a link of the review page"))
        self.configBrowse.setToolTip(_translate("Dialog", "Browse for config file"))
        self.configBrowse.setText(_translate("Dialog", "Browse"))
        self.outputFilePathInputBox.setToolTip(_translate("Dialog", "Path to the output folder"))
        self.outputFolderLabel.setText(_translate("Dialog", "Output Folder"))
        self.outputFolderBrowse.setToolTip(_translate("Dialog", "Browse for output folder"))
        self.outputFolderBrowse.setText(_translate("Dialog", "Browse"))
        self.consoleLabel.setText(_translate("Dialog", "Console:"))
        self.scrappingBtn.setToolTip(_translate("Dialog", "Start the Scrapper"))
        self.scrappingBtn.setText(_translate("Dialog", "Start Scrapping"))
        self.productlabel_1.setText(_translate("Dialog", "Product 1"))
        self.productlabel_2.setText(_translate("Dialog", "Product 2"))
        self.productlabel_3.setText(_translate("Dialog", "Product 3"))
        self.productlabel_4.setText(_translate("Dialog", "Product 4"))
        self.productlabel_5.setText(_translate("Dialog", "Product 5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
